import React, { useEffect, useMemo, useState } from 'react'
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, PieChart, Pie, Cell, LineChart, Line } from 'recharts'
import { supabase } from '../supabaseClient'
import { formatRupiah, formatTanggal, formatTanggalSingkat, toISODateLocal } from '../utils'
import SummaryCards from '../components/SummaryCards'

const WARNA_KATEGORI = ['#2F7A54','#C79A3D','#B1483A','#3C6E71','#8A5A44','#6B7FD7','#A3812F','#4E8098']
function awalBulanIni(){const d=new Date();return toISODateLocal(new Date(d.getFullYear(),d.getMonth(),1))}
function hariIni(){return toISODateLocal(new Date())}
function mundurHari(n){const d=new Date();d.setDate(d.getDate()-(n-1));return toISODateLocal(d)}
function formatLabel(key,bulan=false){if(bulan){const [y,m]=key.split('-');return new Date(+y,+m-1,1).toLocaleDateString('id-ID',{month:'short',year:'2-digit'})}const [y,m,d]=key.split('-');return new Date(+y,+m-1,+d).toLocaleDateString('id-ID',{day:'numeric',month:'short'})}
function downloadBlob(content,fileName,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=fileName;a.click();URL.revokeObjectURL(url)}
function exportExcel(rows,a,b){const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;');const html=`<html><meta charset="utf-8"><body><h2>Laporan Keuangan Uangku</h2><p>Periode: ${formatTanggal(a)} s/d ${formatTanggal(b)}</p><table border="1"><tr><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Nominal</th><th>Sumber/Tujuan</th><th>Keterangan</th><th>Pencatat</th><th>Waktu Pencatatan</th></tr>${rows.map(t=>`<tr><td>${esc(formatTanggal(t.tanggal))}</td><td>${esc(t.tipe)}</td><td>${esc(t.kategori)}</td><td>${Number(t.jumlah)}</td><td>${esc(t.sumber_tujuan)}</td><td>${esc(t.keterangan)}</td><td>${esc(t.profiles?.nama_tampilan)}</td><td>${esc(new Date(t.created_at).toLocaleString('id-ID'))}</td></tr>`).join('')}</table></body></html>`;downloadBlob('\ufeff'+html,`laporan-uangku-${a}-sd-${b}.xls`,'application/vnd.ms-excel;charset=utf-8')}
function exportPdf(rows,a,b,mi,mk){const win=window.open('','_blank','width=1200,height=800');if(!win)return alert('Popup diblokir browser. Izinkan popup untuk mencetak laporan.');const body=rows.map(t=>`<tr><td>${formatTanggal(t.tanggal)}</td><td>${t.tipe==='pemasukan'?'Pemasukan':'Pengeluaran'}</td><td>${t.kategori}</td><td>${formatRupiah(t.jumlah)}</td><td>${t.sumber_tujuan||'—'}</td><td>${t.keterangan||'—'}</td><td>${t.profiles?.nama_tampilan||'—'} (${t.profiles?.peran||'Anggota'})</td><td>${new Date(t.created_at).toLocaleString('id-ID')}</td></tr>`).join('');win.document.write(`<html><head><title>Laporan Uangku</title><style>body{font-family:Arial;padding:25px;color:#222}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #ccc;padding:6px;text-align:left}th{background:#eee}.cards{display:flex;gap:10px}.card{border:1px solid #ddd;padding:10px}.card b{display:block;font-size:18px;margin-top:4px}@media print{button{display:none}}</style></head><body><h1>Laporan Keuangan Uangku</h1><p>Periode ${formatTanggal(a)} s/d ${formatTanggal(b)}</p><div class="cards"><div class="card">Pemasukan<b>${formatRupiah(mi)}</b></div><div class="card">Pengeluaran<b>${formatRupiah(mk)}</b></div><div class="card">Saldo Periode<b>${formatRupiah(mi-mk)}</b></div></div><br/><table><tr><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Nominal</th><th>Sumber/Tujuan</th><th>Keterangan</th><th>Pencatat</th><th>Waktu</th></tr>${body||'<tr><td colspan="8">Tidak ada transaksi.</td></tr>'}</table><script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>`);win.document.close()}

export default function Laporan(){
 const [semua,setSemua]=useState([]),[tanggalAwal,setTanggalAwal]=useState(awalBulanIni()),[tanggalAkhir,setTanggalAkhir]=useState(hariIni()),[search,setSearch]=useState(''),[tipeFilter,setTipeFilter]=useState('semua'),[kategoriFilter,setKategoriFilter]=useState('semua'),[kategoriPemasukan,setKategoriPemasukan]=useState('semua'),[visible,setVisible]=useState(5)
 async function muatData(){const {data}=await supabase.from('transaksi').select('*, profiles(nama_tampilan, peran)').order('tanggal',{ascending:false}).order('created_at',{ascending:false});setSemua(data||[])}
 useEffect(()=>{muatData();const c=supabase.channel('laporan-realtime').on('postgres_changes',{event:'*',schema:'public',table:'transaksi'},muatData).subscribe();return()=>supabase.removeChannel(c)},[])
 const dataRange=useMemo(()=>semua.filter(t=>t.tanggal>=tanggalAwal&&t.tanggal<=tanggalAkhir),[semua,tanggalAwal,tanggalAkhir])
 const kategoriOptions=useMemo(()=>[...new Set(dataRange.map(t=>t.kategori))].sort(),[dataRange])
 const dataTersaring=useMemo(()=>{const q=search.trim().toLowerCase();return dataRange.filter(t=>{const text=[t.kategori,t.sumber_tujuan,t.keterangan,t.profiles?.nama_tampilan,t.profiles?.peran,t.tanggal].filter(Boolean).join(' ').toLowerCase();return (tipeFilter==='semua'||t.tipe===tipeFilter)&&(kategoriFilter==='semua'||t.kategori===kategoriFilter)&&(!q||text.includes(q))})},[dataRange,search,tipeFilter,kategoriFilter])
 useEffect(()=>setVisible(5),[search,tipeFilter,kategoriFilter,tanggalAwal,tanggalAkhir])
 const totalMasuk=dataRange.filter(t=>t.tipe==='pemasukan').reduce((s,t)=>s+Number(t.jumlah),0), totalKeluar=dataRange.filter(t=>t.tipe==='pengeluaran').reduce((s,t)=>s+Number(t.jumlah),0)
 const jumlahHari=Math.max(1,Math.round((new Date(tanggalAkhir)-new Date(tanggalAwal))/86400000)+1), pakaiPerBulan=jumlahHari>62
 const dataPemasukan=useMemo(()=>groupDaily(dataRange.filter(t=>t.tipe==='pemasukan'&&(kategoriPemasukan==='semua'||t.kategori===kategoriPemasukan)),pakaiPerBulan,'pemasukan'),[dataRange,pakaiPerBulan,kategoriPemasukan])
 const dataPengeluaran=useMemo(()=>groupDaily(dataRange.filter(t=>t.tipe==='pengeluaran'),false,'pengeluaran'),[dataRange])
 const incomePie=useMemo(()=>groupCategory(dataRange,'pemasukan'),[dataRange]), expensePie=useMemo(()=>groupCategory(dataRange,'pengeluaran'),[dataRange])
 const previous=useMemo(()=>{const days=jumlahHari;const end=new Date(tanggalAwal+'T00:00:00');end.setDate(end.getDate()-1);const start=new Date(end);start.setDate(start.getDate()-days+1);const a=toISODateLocal(start),b=toISODateLocal(end);const rows=semua.filter(t=>t.tanggal>=a&&t.tanggal<=b);return {a,b,masuk:rows.filter(t=>t.tipe==='pemasukan').reduce((s,t)=>s+Number(t.jumlah),0),keluar:rows.filter(t=>t.tipe==='pengeluaran').reduce((s,t)=>s+Number(t.jumlah),0)}},[semua,tanggalAwal,jumlahHari])
 const delta=(now,old)=>old===0?(now===0?'0%':'Baru'):((now-old)/old*100).toFixed(1)+'%'
 function preset(p){if(p==='7hari'){setTanggalAwal(mundurHari(7));setTanggalAkhir(hariIni())}if(p==='30hari'){setTanggalAwal(mundurHari(30));setTanggalAkhir(hariIni())}if(p==='bulan'){setTanggalAwal(awalBulanIni());setTanggalAkhir(hariIni())}if(p==='semua'){setTanggalAwal(semua.length?semua.reduce((a,b)=>a.tanggal<b.tanggal?a:b).tanggal:hariIni());setTanggalAkhir(hariIni())}}
 return <div style={{maxWidth:1180,margin:'0 auto',padding:'1.4rem'}}><div style={{marginBottom:'1.2rem'}}><h2 style={{fontSize:'1.5rem'}}>Laporan Keuangan</h2><p style={{color:'#3C554C',marginTop:4}}>Analisis lengkap dengan grafik harian, kategori, perbandingan periode, pencarian, dan export.</p></div>
 <div className="card" style={{padding:'1rem 1.2rem',marginBottom:'1.4rem'}}><div style={{display:'flex',gap:'.5rem',flexWrap:'wrap',marginBottom:'.9rem'}}>{[['7hari','7 Hari'],['30hari','30 Hari'],['bulan','Bulan Ini'],['semua','Semua']].map(([k,l])=><button className="btn btn-ghost" key={k} onClick={()=>preset(k)}>{l}</button>)}</div><div style={{display:'flex',gap:'.9rem',flexWrap:'wrap',alignItems:'flex-end'}}><div className="field" style={{margin:0}}><label>Dari tanggal</label><input type="date" value={tanggalAwal} max={tanggalAkhir} onChange={e=>setTanggalAwal(e.target.value)}/></div><div className="field" style={{margin:0}}><label>Sampai tanggal</label><input type="date" value={tanggalAkhir} min={tanggalAwal} max={hariIni()} onChange={e=>setTanggalAkhir(e.target.value)}/></div><button className="btn btn-primary" onClick={()=>exportPdf(dataTersaring,tanggalAwal,tanggalAkhir,totalMasuk,totalKeluar)}>Cetak / Export PDF</button><button className="btn btn-ghost" onClick={()=>exportExcel(dataTersaring,tanggalAwal,tanggalAkhir)}>Export Excel</button></div></div>
 <SummaryCards totalMasuk={totalMasuk} totalKeluar={totalKeluar}/>
 <div className="card comparison-card"><h3>Perbandingan dengan periode sebelumnya</h3><div className="comparison-grid"><div><span>Pemasukan</span><strong>{formatRupiah(totalMasuk)}</strong><small>{delta(totalMasuk,previous.masuk)} dari {formatTanggal(previous.a)}–{formatTanggal(previous.b)}</small></div><div><span>Pengeluaran</span><strong>{formatRupiah(totalKeluar)}</strong><small>{delta(totalKeluar,previous.keluar)} dari periode sebelumnya</small></div><div><span>Saldo periode</span><strong>{formatRupiah(totalMasuk-totalKeluar)}</strong><small>Periode aktif</small></div></div></div>
 <div className="card" style={{padding:'1rem 1.2rem',margin:'1.4rem 0'}}><div className="report-filters"><div className="field" style={{margin:0}}><label>Cari transaksi</label><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Kategori, keterangan, pencatat, tanggal…"/></div><div className="field" style={{margin:0}}><label>Jenis</label><select value={tipeFilter} onChange={e=>setTipeFilter(e.target.value)}><option value="semua">Semua</option><option value="pemasukan">Pemasukan</option><option value="pengeluaran">Pengeluaran</option></select></div><div className="field" style={{margin:0}}><label>Kategori</label><select value={kategoriFilter} onChange={e=>setKategoriFilter(e.target.value)}><option value="semua">Semua kategori</option>{kategoriOptions.map(k=><option key={k}>{k}</option>)}</select></div></div><p className="hint">Menampilkan {dataTersaring.length} hasil pencarian dari {dataRange.length} transaksi periode aktif.</p></div>
 <div className="chart-grid"><ChartCard title={`Pemasukan ${pakaiPerBulan?'per Bulan':'per Hari'}`} control={<select value={kategoriPemasukan} onChange={e=>setKategoriPemasukan(e.target.value)}><option value="semua">Semua kategori</option>{kategoriOptions.filter(k=>dataRange.some(t=>t.tipe==='pemasukan'&&t.kategori===k)).map(k=><option key={k}>{k}</option>)}</select>}>{dataPemasukan.length?<ResponsiveContainer width="100%" height={280}><BarChart data={dataPemasukan}><CartesianGrid strokeDasharray="3 3" stroke="#EFE9D9"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={v=>v>=1000000?`${v/1000000}jt`:`${v/1000}rb`}/><Tooltip formatter={v=>formatRupiah(v)}/><Bar dataKey="value" name="Pemasukan" fill="#2F7A54" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<EmptyChart/>}</ChartCard>
 <ChartCard title="Pengeluaran per Hari"><ResponsiveContainer width="100%" height={280}><LineChart data={dataPengeluaran}><CartesianGrid strokeDasharray="3 3" stroke="#EFE9D9"/><XAxis dataKey="label" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}} tickFormatter={v=>v>=1000000?`${v/1000000}jt`:`${v/1000}rb`}/><Tooltip formatter={v=>formatRupiah(v)}/><Line type="monotone" dataKey="value" name="Pengeluaran" stroke="#B1483A" strokeWidth={2}/></LineChart></ResponsiveContainer></ChartCard>
 <ChartCard title="Pemasukan berdasarkan Kategori"><PieOrEmpty data={incomePie}/></ChartCard><ChartCard title="Pengeluaran berdasarkan Kategori"><PieOrEmpty data={expensePie}/></ChartCard></div>
 <div className="card" style={{marginTop:'1.4rem',overflow:'hidden'}}><div style={{padding:'1rem 1.2rem',borderBottom:'1px solid #EFE9D9'}}><h3 style={{fontSize:'1rem',margin:0}}>Detail Transaksi</h3></div><div style={{overflowX:'auto'}}><table className="report-table"><thead><tr><th>Tanggal</th><th>Jenis</th><th>Kategori</th><th>Nominal</th><th>Sumber/Tujuan</th><th>Keterangan</th><th>Dicatat oleh</th><th>Waktu pencatatan</th></tr></thead><tbody>{dataTersaring.length===0?<tr><td colSpan="8" style={{textAlign:'center',padding:'1.5rem'}}>Tidak ada transaksi.</td></tr>:dataTersaring.slice(0,visible).map(t=><tr key={t.id}><td>{formatTanggalSingkat(t.tanggal)}</td><td>{t.tipe==='pemasukan'?'Pemasukan':'Pengeluaran'}</td><td>{t.kategori}</td><td className="mono" style={{fontWeight:700,color:t.tipe==='pemasukan'?'#2F7A54':'#B1483A'}}>{formatRupiah(t.jumlah)}</td><td>{t.sumber_tujuan||'—'}</td><td>{t.keterangan||'—'}</td><td>{t.profiles?.nama_tampilan||'—'}<br/><small>{t.profiles?.peran||'Anggota'}</small></td><td>{new Date(t.created_at).toLocaleString('id-ID')}</td></tr>)}</tbody></table></div>{dataTersaring.length>5&&<div className="load-more-wrap">{visible<dataTersaring.length?<button className="btn btn-ghost" onClick={()=>setVisible(v=>v+5)}>Lihat Selengkapnya ({Math.min(5,dataTersaring.length-visible)} lagi)</button>:<button className="btn btn-ghost" onClick={()=>setVisible(5)}>Tampilkan lebih sedikit</button>}</div>}</div>
 <style>{`.report-filters{display:grid;grid-template-columns:1.5fr 1fr 1fr;gap:.8rem}.chart-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.4rem;margin-top:1.4rem}.comparison-card{padding:1.2rem;margin-top:1.4rem}.comparison-card h3{font-size:1rem;margin:0 0 1rem}.comparison-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem}.comparison-grid>div{border:1px solid #EFE9D9;border-radius:10px;padding:.9rem}.comparison-grid span,.comparison-grid small{display:block;color:#8A7F68;font-size:.76rem}.comparison-grid strong{display:block;font-size:1.1rem;margin:.3rem 0}.report-table{width:100%;border-collapse:collapse;font-size:.78rem}.report-table th,.report-table td{padding:.7rem .8rem;border-bottom:1px solid #EFE9D9;text-align:left;vertical-align:top;white-space:nowrap}.report-table th{background:#FFFDF7;color:#3C554C}.load-more-wrap{text-align:center;padding:1rem}.hint{font-size:.76rem;color:#8A7F68}.pie-report-wrap{display:flex;flex-direction:column;min-width:0}.pie-chart-box{width:100%;min-width:0}.pie-category-list{display:flex;flex-direction:column;gap:.45rem;margin-top:.35rem;border-top:1px solid #EFE9D9;padding-top:.7rem}.pie-category-item{display:flex;justify-content:space-between;align-items:center;gap:.8rem;font-size:.74rem;min-width:0}.pie-category-name{display:flex;align-items:center;gap:.45rem;min-width:0;color:#3C554C}.pie-category-name i{width:9px;height:9px;border-radius:50%;flex:0 0 auto}.pie-category-name{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.pie-category-value{color:#8A7F68;text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}@media(max-width:780px){.chart-grid,.comparison-grid,.report-filters{grid-template-columns:1fr!important}.pie-category-item{align-items:flex-start}.pie-category-value{font-size:.7rem}}`}</style></div>
}
function groupDaily(rows,bulan,mode){const m={};rows.forEach(t=>{const key=bulan?t.tanggal.slice(0,7):t.tanggal;if(!m[key])m[key]={key,value:0};m[key].value+=Number(t.jumlah)});return Object.values(m).sort((a,b)=>a.key.localeCompare(b.key)).map(x=>({...x,label:formatLabel(x.key,bulan),mode}))}
function groupCategory(rows,tipe){const m={};rows.filter(t=>t.tipe===tipe).forEach(t=>m[t.kategori]=(m[t.kategori]||0)+Number(t.jumlah));return Object.entries(m).map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function ChartCard({title,control,children}){return <div className="card" style={{padding:'1.3rem'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:'.6rem',marginBottom:'1rem',flexWrap:'wrap'}}><h3 style={{fontSize:'1rem',margin:0}}>{title}</h3>{control}</div>{children}</div>}
function PieOrEmpty({data}){
 if(!data.length)return <EmptyChart/>;
 const total=data.reduce((s,d)=>s+Number(d.value),0);
 return <div className="pie-report-wrap">
   <div className="pie-chart-box">
     <ResponsiveContainer width="100%" height={230}>
       <PieChart>
         <Pie data={data} dataKey="value" nameKey="name" outerRadius="72%" paddingAngle={2} label={false} labelLine={false}>
           {data.map((_,i)=><Cell key={i} fill={WARNA_KATEGORI[i%WARNA_KATEGORI.length]}/>)}
         </Pie>
         <Tooltip formatter={v=>formatRupiah(v)}/>
       </PieChart>
     </ResponsiveContainer>
   </div>
   <div className="pie-category-list">
     {data.map((item,i)=>{const pct=total?((Number(item.value)/total)*100).toFixed(1):'0.0';return <div className="pie-category-item" key={item.name}>
       <span className="pie-category-name"><i style={{background:WARNA_KATEGORI[i%WARNA_KATEGORI.length]}}></i>{item.name}</span>
       <span className="pie-category-value">{pct}% · {formatRupiah(item.value)}</span>
     </div>})}
   </div>
 </div>
}
function EmptyChart(){return <p style={{color:'#8A7F68',textAlign:'center',padding:'2rem 0'}}>Belum ada data pada rentang ini.</p>}
